name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build the Docker image
      run: |
        TAG=$(date +%Y%m%d)
        docker build . --file Dockerfile --tag rohithvp/short_url:$TAG
        echo $TAG > TAG_FILE

    - name: Push Docker image to Docker Hub
      run: |
        TAG=$(cat TAG_FILE)
        docker push rohithvp/short_url:$TAG

